### ISSUE TITLE
Docker for mac fails on: docker-compose up ./docker-compose.proxy-example.yml

### ISSUE THREAD

**Issue by joeblew99** [ZZROTDesign/alpine-caddy#10]
Might be my lack of experience, but cant get docker-compose up to start the proxy example.

I am using the Docker for Mac:
Version 1.12.0-rc2-beta17 (build: 9779)

Googling around for solution found a few red herrings. So posting here to see if anyone sees what i am doing wrong.

Heres my attempt:

```
x-MacBook-Pro:examples apple$ pwd
/Users/apple/workspace/go/src/bitbucket.org/joe/md-x/_docs/Tech/Docker/alpine-caddy/examples
x-MacBook-Pro:examples apple$ ls -al
total 24
drwxr-xr-x   5 apple  staff  170 Jul  5 14:18 .
drwxr-xr-x  19 apple  staff  646 Jul  5 14:18 ..
-rw-r--r--   1 apple  staff  727 Jul  5 14:18 Caddyfile.proxy.example
-rw-r--r--   1 apple  staff  240 Jul  5 14:18 docker-compose.example.yml
-rw-r--r--   1 apple  staff  597 Jul  5 14:18 docker-compose.proxy-example.yml
x-MacBook-Pro:examples apple$ docker-compose up ./docker-compose.proxy-example.yml
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

```

**Comment by kilpatty** [comment]
try docker-compose -f docker-compose.proxy-example.yml

Do this inside of the same directory that the docker-compose.proxy-example.yml file exists :). Let me know if you have any more questions. (Also note that the example files may not bring fully working functionality out of the box, as they are meant to be more of a guidance in writing your own.

**Comment by joeblew99** [comment]
@Skilgarriff 

i am doing it in the same dir, but no luck. 
When i run it nothing at all happens except the standard help output. Its not saying that docker-compose file does not exist at least now that the -f (--file) was added to the command line.

my versions -
These versions are new. The standard docker for Mac update ran on my Macbook tonight.
DO you have the same version i wonder ?
Docker for mac version 1.12.0-rc3-beta18 (build: 9969)
Docker version 1.12.0-rc3, build 91e29e8, experimental
Docker-compose version 1.8.0-rc1, build 9bf6bc6

**Comment by joeblew99** [comment]
got more luck with the "up" at the end
but now got a "not a directory"

```
docker-compose -f docker-compose.proxy-example.yml up
Creating network "examples_frontend" with the default driver
Pulling example-blog (zzrot/alpine-ghost:latest)...
latest: Pulling from zzrot/alpine-ghost
6d6a6a7dae29: Already exists
417f0c1a928b: Pull complete
9d7dc17b812e: Pull complete
36ee4c5a2a05: Pull complete
c601005fff6c: Pull complete
3555209b4f0f: Pull complete
372d4ccc331d: Pull complete
Digest: sha256:fe7fc240d9888ea7e39b4b921cdfc11cf39b3f712795e20cde4362336b760437
Status: Downloaded newer image for zzrot/alpine-ghost:latest
Creating examples_example-server_1
Creating examples_example-blog_1
Creating examples_proxy_1

ERROR: for proxy  oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/d31dedf05fe66093ce7fa18a3e711847875687343fc6b90af00e7b3ab6733b81/etc/Caddyfile" to rootfs "/var/lib/docker/aufs/mnt/d31dedf05fe66093ce7fa18a3e711847875687343fc6b90af00e7b3ab6733b81" caused "not a directory"
ERROR: Encountered errors while bringing up the project.
x-MacBook-Pro:examples apple$ 
```

**Comment by joeblew99** [comment]
The simpler example gets the exact same error, so thats at least consistent.
Seems to be a path issue. 

```
docker-compose -f docker-compose.example.yml up
Creating examples_web_1

ERROR: for web  oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/60945ce565329512c760503a6a5fd9cc72efc9c564192d8056fe1140d659b2bb/etc/Caddyfile" to rootfs "/var/lib/docker/aufs/mnt/60945ce565329512c760503a6a5fd9cc72efc9c564192d8056fe1140d659b2bb" caused "not a directory"
ERROR: Encountered errors while bringing up the project.
x-MacBook-Pro:examples apple$ 
```

**Comment by joeblew99** [comment]
i got the compose working:

```
docker-compose -f docker-compose.example.yml up
Creating examples_web_1
Attaching to examples_web_1
web_1  | jack is incompatible with use of CloseNotifier in same ServeHTTP call
examples_web_1 exited with code 137
```

I did not quite understand the readme, regarding copying the files into the examples dir.
Once i copied the public folder (with the index inside) and the Caddfile, into the examples dir, everything worked.

I am pretty new at this, but learnt allot. Can stay CLOSED - thanks for the help

**Comment by Banashek** [comment]
I'm having this same issue `oci runtime error` specific to mounting the Caddyfile in the container.

What ended up being the solution for you?

The error for me:

```
ERROR: for caddy  Cannot start service caddy: invalid header field value "oci runtime error: 
container_linux.go:247: starting container process caused \"
process_linux.go:359: container init caused \\\"
rootfs_linux.go:53: mounting 
\\\\\\\"/Users/jonbanashek/Projects/fs/lh/Caddyfile\\\\\\\" to rootfs 
\\\\\\\"/var/lib/docker/aufs/mnt/e501fe2a9cbf5a64c913592862204dc5d6d31856f69ec43b164c46355ab23776\\\\\\\" 
at \\\\\\\"/var/lib/docker/aufs/mnt/e501fe2a9cbf5a64c913592862204dc5d6d31856f69ec43b164c46355ab23776/etc/Caddyfile\\\\\\\"
 caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
```

It seems as though it can't find the `/etc` directory on the docker host.

This is when using docker-compose to deploy to a digitalocean droplet (configured via docker-machine) fyi.

Caddyfile:

```
www.mysite.com, mysite.com {

    proxy / web:80 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }

    header / {
        #Include any headers for your site here
    }

    gzip

    tls my@email.com
}

```

Any ideas?
