### ISSUE TITLE
should we enable quic by default?

### ISSUE THREAD

**Issue by kilpatty** [ZZROTDesign/alpine-caddy#22]
I'm contemplating enabling quic by default for this image. I'm not sure if that would make any problems arise for anybody as it should default to not using quic if it is not supported.

Any objections to this should be contained in this issue.

**Comment by killianbrackey** [comment]
As far as I know this should be fine.  Is quic completely compatible with UDP dependent applications?

**Comment by kilpatty** [comment]
I think so - going to merge it in for now - if anyone reports issues with it, we can roll back
