### ISSUE TITLE
Container not restarting on docker-gen notify-sighup

### ISSUE THREAD

**Issue by whitestrake** [ZZROTDesign/alpine-caddy#8]
Hi guys,

I'm trying to configure docker-gen to template the Caddyfile to reverse proxy a few services.

I've noted that the caddy container does not seem to restart when sent a sighup. I have no idea if this is an issue with docker, caddy, or alpine-caddy.

Running Docker 1.11.2 on Ubuntu as well as 1.11.1-beta13.1 on a Mac, using `docker kill -s hup <container>` seems to restart any other given container in my `docker-compose.yml`, as expected, except for caddy which never comes back up again. `docker restart caddy` does restart the container properly, but I'm not sure I can achieve this from within the docker-gen container.

Edit: This appears to be caddy specific behaviour

**Comment by killianbrackey** [comment]
Thanks for the  update and for closing! If you get the chance update us on the issue as it evolves -- we will try to do the same!

**Comment by whitestrake** [comment]
I don't know if any of my findings thus far are specific to this container at all, but so far I note that the caddy developer actually implemented restarts on SIGUSR1 rather than SIGHUP, which should be achievable with a docker-gen conf file.

I've made a few observations, but my understanding is limited as I consider myself still just a linux/docker learner. I may be reaching beyond my expertise at the moment.
1. `kill -l` shows a value of 10 for SIGUSR1 on Ubuntu 14.04 and the same value for USR1 in Alpine.
2. When caddy is executed on the Ubuntu host, it does restart when sent SIGUSR1, with a new PID.
3. Using `docker exec -it alpine-caddy /bin/sh` and sending `kill -s 10 1` to the caddy process kills the alpine-caddy container.
4. Creating an abiosoft/caddy container, and sending `kill -s 10 1` via `/bin/sh` to the caddy process DOES restart the container, but unfortunately `docker kill -s 10 abiosoft-caddy` from host still does not restart.

Don't know if this is the best place to discuss what I'm trying to achieve but I'd love some direction if you have any ideas.

I've briefly entertained the idea of building an image from docker-gen and including the Docker client as we're already mounting docker.sock, could then send `docker restart caddy` from within the docker-gen container... Not sure.

edit: I found caddy's logging switch: `docker run --name caddy-test zzrot/alpine-caddy caddy --log stdout`. Sending `docker kill -s 10 caddy-test` and checking logs:

```
2016/06/08 00:28:31 [WARNING] Root path does not exist: /var/www/html
Activating privacy features... done.
0.0.0.0:80
2016/06/08 00:28:51 [INFO] SIGUSR1: Reloading
2016/06/08 00:28:51 [INFO] Restarting
2016/06/08 00:28:51 [WARNING] Root path does not exist: /var/www/html
2016/06/08 00:28:51 [WARNING] Root path does not exist: /var/www/html
```

Then the container exits. Is it because of tini?

**Comment by whitestrake** [comment]
Looks like Caddy starts a new process with a new PID upon receiving SIGUSR1 instead of reusing the PID. This kills tini, which kills the container. I did some research and tried making an image with [supervisord](https://docs.docker.com/engine/admin/using_supervisord/) which stops and restarts nominated processes when it receives SIGHUP.

```
FROM zzrot/alpine-caddy:latest
MAINTAINER Whitestrake <docker@whitestrake.net>

RUN apk --no-cache add supervisor

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord"]
CMD ["--configuration", "/etc/supervisor/conf.d/supervisord.conf"]
```

With supervisord.conf:

```
[supervisord]
nodaemon=true

[program:caddy]
command=caddy --conf /etc/Caddyfile
```

Which has a result I like more:

```
2016-06-09 05:30:52,025 CRIT Supervisor running as root (no user in config file)
2016-06-09 05:30:52,027 INFO supervisord started with pid 1
2016-06-09 05:30:53,030 INFO spawned: 'caddy' with pid 7
2016-06-09 05:30:54,041 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-06-09 05:31:04,468 WARN received SIGHUP indicating restart request
2016-06-09 05:31:04,469 INFO waiting for caddy to die
2016-06-09 05:31:04,469 INFO stopped: caddy (exit status 0)
2016-06-09 05:31:04,473 CRIT Supervisor running as root (no user in config file)
2016-06-09 05:31:04,476 INFO supervisord started with pid 1
2016-06-09 05:31:05,479 INFO spawned: 'caddy' with pid 14
2016-06-09 05:31:06,490 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

But nearly doubles the image size. :(

Also means we're manually killing and restarting Caddy, avoiding it's built-in configuration fallback if the newly provided Caddyfile isn't valid. So the docker-gen template would have to be rock solid.

**Comment by whitestrake** [comment]
Found a neater solution.

Dockerfile:

```
FROM zzrot/alpine-caddy:latest
MAINTAINER Whitestrake <docker@whitestrake.net>

COPY entry.sh /usr/bin/entry.sh

ENTRYPOINT ["/usr/bin/entry.sh"]
CMD ["--conf", "/etc/Caddyfile"]
```

With entry.sh:

```
#!/bin/sh

# SIGHUP
hup_handler() {
  pid=`cat /etc/caddy.pid`
  echo "[entry.sh] Received SIGHUP, sending SIGUSR1 to $pid"
  kill -10 "$pid"
  hover
}

# Wait on caddy
hover() {
  sleep 1
  pid=`cat /etc/caddy.pid`
  echo "[entry.sh] Now waiting on $pid"
  wait "$pid"
}

trap 'hup_handler' SIGHUP

echo "[entry.sh] Starting caddy with args $@"
caddy -log stdout -pidfile /etc/caddy.pid "$@" &
hover
```

Starting a test container and sending SIGHUP to it:

```
[entry.sh] Starting caddy with args --conf /etc/Caddyfile
2016/06/10 02:14:49 [WARNING] Root path does not exist: /var/www/html
Activating privacy features... done.
0.0.0.0:80
[entry.sh] Now waiting on 5
[entry.sh] Received SIGHUP, sending SIGUSR1 to 5
2016/06/10 02:19:53 [INFO] SIGUSR1: Reloading
2016/06/10 02:19:53 [INFO] Restarting
2016/06/10 02:19:53 [WARNING] Root path does not exist: /var/www/html
2016/06/10 02:19:53 [WARNING] Root path does not exist: /var/www/html
[entry.sh] Now waiting on 16
```

Can sort of do whatever we want with the signal handlers. Will probably implement the other caddy signal handlers as well..

**Comment by whitestrake** [comment]
Caddy beta 0.9 updates SIGUSR1 handling to graceful reload without spawning a new process:

https://forum.caddyserver.com/t/caddy-0-9-beta-version-available/146

Everything above should be completely unnecessary after that.
